### ISSUE TITLE
WidgetStateProperty Issue.

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [El-Mazouzi/custom_date_range_picker#14]
`../../.pub-cache/hosted/pub.dev/custom_date_range_picker-1.1.0/lib/custom_date_range_picker.dart:227:43: Error: The getter 'WidgetStateProperty' isn't defined for the class 'CustomDateRangePickerState'.
 - 'CustomDateRangePickerState' is from 'package:custom_date_range_picker/custom_date_range_picker.dart' ('../../.pub-cache/hosted/pub.dev/custom_date_range_picker-1.1.0/lib/custom_date_range_picker.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'WidgetStateProperty'.
                                    side: WidgetStateProperty.all(`

<img width="1456" alt="Screenshot 2024-06-02 at 3 15 01 AM" src="https://github.com/El-Mazouzi/custom_date_range_picker/assets/65047962/be0b8d5a-49d3-4c31-be0b-976cd9fd3079">

My Flutter Doctor Reports in Intl version is both compatible.
Cleared Cache, Repair IDE also through dart pub repair cache

**Comment by El-Mazouzi** [comment]
can you please run flutter doctor

**Comment by Dev-Muhammad-Junaid** [comment]
Here you go.

```
`[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-arm64, locale en-PK)
    • Flutter version 3.19.3 on channel stable at /Users/jd/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ba39319843 (3 months ago), 2024-03-07 15:22:21 -0600
    • Engine revision 2e4ba9c6fb
    • Dart version 3.3.1
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jd/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15F31d
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 125.0.6422.113
    ! Error: Browsing on the local area network for iPhone 11 pro. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this
      Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
`
```

**Comment by El-Mazouzi** [comment]
yes, you have to upgrade your flutter sdk to  latest version 3.22.0
because `WidgetStateProperty` was introduced in this version

**Comment by Dev-Muhammad-Junaid** [comment]
But i had same issue in the version from 14 months ago. Not sure why

**Comment by El-Mazouzi** [comment]
Sorry, I didn’t understand what you mean.
can you please upgrade your flutter sdk and try again?

**Comment by Dev-Muhammad-Junaid** [comment]
Currently, I can only work with flutter SDK 3.19
However, I tried using the 1.0.10
<https://pub.dev/packages/custom_date_range_picker/versions/1.0.10> version
but also got the same error.

**Comment by El-Mazouzi** [comment]
Since you have to work only with flutter SDK 3.19
I recommend you to create a branch and update it as it works for you

**Comment by Dev-Muhammad-Junaid** [comment]
Thanks for the tip. I appreciate it.
