### ISSUE TITLE
backgroundColor and primaryColor don't do anything 

### ISSUE THREAD

**Issue by alastairrmcneill** [El-Mazouzi/custom_date_range_picker#5]
<img width="1880" alt="Screenshot 2023-03-27 at 09 19 13" src="https://user-images.githubusercontent.com/52216324/227883028-9385eea0-ac95-47a0-9ace-2c2eef54d254.png">
When setting the backgroundColor and the primaryColor in the code the dialog box doesn't change its look

**Comment by El-Mazouzi** [comment]
please upgrade to the lateset version **1.0.10**
[https://pub.dev/packages/custom_date_range_picker](url)
