### ISSUE TITLE
bug in picking one day , (no start date, no end) , 

### ISSUE THREAD

**Issue by abdessamadpas** [El-Mazouzi/custom_date_range_picker#7]
![image](https://github.com/El-Mazouzi/custom_date_range_picker/assets/53188247/bbfc7849-b879-4b6b-8bae-44a7ef68148f)
i just wanna pick one day and filtter my data using it
any solution ?❤️‍🔥

**Comment by El-Mazouzi** [comment]
with this package you can't pick only one day , I recommand using `showDatePicker`
